spring:
  datasource:
    url: jdbc:h2:mem:todos-test;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
logging:
  level:
    org.hibernate.SQL: warn
