spring:
  datasource:
    url: jdbc:h2:file:./data/todos;DB_CLOSE_DELAY=-1;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  h2:
    console.enabled: true
    console.settings.web-allow-others: true
  # OAuth2 Configuration
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:your-google-client-id}
            client-secret: ${GOOGLE_CLIENT_SECRET:your-google-client-secret}
            scope: openid,email,profile
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"

server:
  port: 8080

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  packages-to-scan: com.aliunal.todoservice.api
  show-actuator: false

# Security Configuration
security:
  jwt:
    secret: ${JWT_SECRET:your-default-secret-key-that-should-be-at-least-256-bits-long-for-security}
    access-token-validity: 900000      # 15 minutes in milliseconds
    refresh-token-validity: 604800000  # 7 days in milliseconds

# Application Configuration
app:
  frontend:
    url: ${FRONTEND_URL:http://localhost:3000}
